import React, { Fragment, Component } from 'react';
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/core/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import Paper from '@material-ui/core/Paper';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemText from '@material-ui/core/ListItemText';
import Avatar from '@material-ui/core/Avatar';
import SingleUser from './singleuser';

const styles = theme => ({
    text: {
        paddingTop: theme.spacing.unit * 2,
        paddingLeft: theme.spacing.unit * 2,
        paddingRight: theme.spacing.unit * 2,
    },
    paper: {
        paddingBottom: 50,
    },
    list: {
        marginBottom: theme.spacing.unit * 2,
    },
    subHeader: {
        backgroundColor: theme.palette.background.paper,
    },
    appBar: {
        top: 'auto',
        bottom: 0,
    },
    toolbar: {
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    fabButton: {
        position: 'absolute',
        zIndex: 1,
        top: -30,
        left: 0,
        right: 0,
        margin: '0 auto',
    },
});

const messages = [
    {
        id: 1,
        primary: 'Mariam Sarjveladze',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: 'https://scontent.ftbs6-1.fna.fbcdn.net/v/t1.0-9/21191973_1357176321046510_4540100000086420183_n.jpg?_nc_cat=101&_nc_ht=scontent.ftbs6-1.fna&oh=e00283464aa5c135c582835f65e02bd7&oe=5D502255',
    },
    {
        id: 2,
        primary: 'Nika Sepiskveradze',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: 'https://scontent.ftbs6-1.fna.fbcdn.net/v/t1.0-9/49734909_2584629771577007_6902834578721865728_n.jpg?_nc_cat=105&_nc_ht=scontent.ftbs6-1.fna&oh=494a25524ade46b627ff9716311028a8&oe=5D367012',
    },
    {
        id: 3,
        primary: 'Tornike Gagadze',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: 'https://scontent.ftbs6-1.fna.fbcdn.net/v/t1.0-9/48374996_1963118913764225_834606205396582400_n.jpg?_nc_cat=101&_nc_ht=scontent.ftbs6-1.fna&oh=619e30a3a8afdf9a5ba8e1cddacf13f0&oe=5D3C5459',
    },
    {
        id: 4,
        primary: 'Iuri Sajaia',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: 'https://scontent.ftbs6-1.fna.fbcdn.net/v/t1.0-9/52071488_2265199556877793_7156267812741185536_n.jpg?_nc_cat=104&_nc_ht=scontent.ftbs6-1.fna&oh=0c7c044581d64097442baf8e4b047905&oe=5D3D762B',
    },
    {
        id: 5,
        primary: "Tokio",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: 'https://i.ytimg.com/vi/R2X3ONDxCBQ/maxresdefault.jpg',
    },
    {
        id: 6,
        primary: 'Rio',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: 'https://dippytee.com/pub/media/blog/la-casa-de-papel-cast-te-zien-in-nieuwe-netflix-thriller-elite/rio.jpg',
    }
];


// const { classes } = this.props;
class BottomAppBar extends Component {
    state = {

    }

    // user = messages[0];
    singleFriend = user => {

        this.setState({ user })

    }


    render() {
        const friends = this.props.diary;
        const user = this.state.user;
        console.log(user)
        return (
            <React.Fragment>
                {/* <CssBaseline /> */}
                <div className="row">
                    <div className="col-lg-3 col-md-3 col-sm-12">

                        <Paper square >

                            <List className="questions-list" >
                                {friends ? (
                                    <>
                                        {friends.map(friend => {
                                            return (

                                                <ListItem key={friend._id} onClick={() => this.singleFriend(friend)}>
                                                    <ListItemText primary={friend.from.firstname + ' ' + friend.from.lastname} />
                                                </ListItem>
                                            )
                                        })}
                                    </>
                                ) : null}

                               
                            </List>
                        </Paper>
                    </div>
                    <div className="col-lg-9 col-md-9 col-sm-12">
                        {user ? (
                            <>
                                <h2>{user.from.firstname} {user.from.lastname}</h2>
                                <div className="diary-single">
                                    <div className="friends-questions">
                                      
                                        {user.question.map(q => {
                                            return (
                                                <>
                                                    <li className="questions-li" key={q}>{q}</li>
                                                </>
                                            )
                                        })}

                                        <div className="friends-answers">
                                        
                                            {user.answer.map(a => {
                                                return (
                                                    <>
                                                        <li key={a}>{a}</li>
                                                    </>
                                                )
                                            })}
                                        </div>

                                    </div>

                                </div>
                            </>
                        ) : <p>დღიური ცარიელია</p>}
                    </div>
                </div>

            </React.Fragment>
        );
    }
}

export default BottomAppBar;
